module.exports = [
    {
        "movieName": "KUNG FU PANDA 4",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/03/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp.jpg",
        "ageLimit": "P",
        "language": "Phụ đề/Lồng tiếng",
        "format": "2D",
        "cats": "Animation",
        "description": "Sau khi Po được chọn trở thành Thủ lĩnh tinh thần của Thung lũng Hòa bình, Po cần tìm và huấn luyện một Hiệp Sĩ Rồng mới, trong khi một nữ phù thủy quyền năng đan lên kế hoạch triệu tập lại tất cả những kẻ phản diện bậc thầy mà Po đã đánh bại trước đây.",
        "directors": "Mike Mitchell, Stephanie Stine",
        "actors": "Angelina Jolie, Ke Huy Quan",
        "startDate": "08/03/2024",
        "duration": "95",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "DOGS AT THE OPERA",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/02/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-5.jpg",
        "ageLimit": "P",
        "language": "Phụ đề/Lồng tiếng",
        "format": "2D",
        "cats": "Animation",
        "description": "Moscow, đầu thế kỷ 20, chú chó hoang Samson, chạy trốn khỏi những kẻ bắt thú, thấy mình đang ở Nhà hát Bolshoy. Vì vậy, nhân vật chính làm quen với con chó của nữ diễn viên ba lê, sau đó anh ta giúp trả lại đồ trang trí bị đánh cắp của bà chủ.",
        "directors": "Vasiliy Rovenskiy",
        "actors": "Anna Starshenbaum, Garik Kharlamov",
        "startDate": "26/12/2023",
        "duration": "90",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "GẶP LẠI CHỊ BẦU",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/02/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp.png",
        "ageLimit": "P",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Comedy",
        "description": "Một chàng trai với với niềm đam mê diễn xuất nhưng lại có một quá khứ không bình yên, cùng cuộc gặp gỡ định mệnh với một cô giáo hơi \"lố tuổi\" , với câu chào đầu đầy ấn tượng \"Em có ý gì với chị không?\"20/12/2024",
        "directors": "Nhất Trung",
        "actors": "Anh Tu, Lê Giang, Diệu Nhi, Kiều Minh Tuấn",
        "startDate": "10/02/2024",
        "duration": "114",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "MAI",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/02/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-1.jpg",
        "ageLimit": "T18",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Drama",
        "description": "MAI là câu chuyện về cuộc đời của người phụ nữ cùng tên, với ánh nhìn tĩnh lặng, xuyên thấu \" Quá khứ chưa ngủ yên, ngày mai liệu sẽ đến?..\"20/12/2024",
        "directors": "Tran Thanh",
        "actors": "Tuấn Trần, Uyển Ân, Phương Anh Đào",
        "startDate": "10/02/2024",
        "duration": "131",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "NOAH'S ARK",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/01/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-13.jpg",
        "ageLimit": "P",
        "language": "Phụ đề/Lồng tiếng",
        "format": "2D",
        "cats": "Animation",
        "description": "Khi mùa mưa đến, mỗi loài chỉ có một con đực và một con cái được phép lên con tàu của Noah. Với sự giúp đỡ của một con gián khéo léo, hai chú chuột Vini và Tito lẻn lên con tàu và dính vào cuộc chiến giữa loài ăn thịt và loài chỉ ăn được thực vật.Khi mùa mưa đến, mỗi loài chỉ có một con đực và một con cái được phép lên con tàu của Noah. Với sự giúp đỡ của một con gián khéo léo, hai chú chuột Vini và Tito lẻn lên con tàu và dính vào cuộc chiến giữa loài ăn thịt và loài chỉ ăn được thực vật.",
        "directors": "Sergio Machado, René Veilleux",
        "actors": "Marcelo Adnet",
        "startDate": "10/02/2024",
        "duration": "90",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "POPORO THE MOVIE: POP STAR ADVENTURE",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/01/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-92.jpg",
        "ageLimit": "P",
        "language": "Lồng tiếng",
        "format": "2D",
        "cats": "Animation",
        "description": "Pororo và những nngười bạn chỉ còn cách chiến thắng trong cuộc thi âm nhạc mà họ tham gia vốn chỉ để giải trí. Liệu Poporo và những người bạn có sống sót sau sự phiền nhiễu của Big Ben và giành chiến thắng?",
        "directors": "Yoon Je-wan",
        "actors": "20/12/2024",
        "startDate": "23/02/2024",
        "duration": "77",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "DEMON SLAYER: TO THE HASHIRA TRAINING",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/03/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-2.jpg",
        "ageLimit": "T16",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Animation",
        "description": "Lấy bối cảnh ở làng thợ rèn vàhồi kết của trận ác chiến giữa Tanjiro với Thượng Huyền Tứ Hantengu và việc Nezuko khắc chế được mặt trời. Tập đầu tiên của phần Đại Trụ Đặc Huấn, mở màn cho khóa đặc huấn của các Đại Trụ cho cuộc quyết chiến với Kibutsuji",
        "directors": "20/12/2024",
        "actors": "Yoshitsugu Matstuoka, Natsuki Hanae",
        "startDate": "23/02/2024",
        "duration": "103",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "SPY x FAMILY CODE: WHITE",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/02/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp.jpg",
        "ageLimit": "T13",
        "language": "Phụ đề/Lồng tiếng",
        "format": "2D",
        "cats": "Animation",
        "description": "Bộ phim xoay quanh 1 gia đình điệp viên có 1-0-2: Loid và Yor là 2 điệp viên phải kết hôn giả với nhau và để thuận tiện che mắt, họ nhận nuôi cô bé Anya. Nhiệm vụ của bố Loid và mẹ Yor là ngăn chặn chiến tranh và bảo vệ hòa bình…",
        "directors": "Kazuhiro Furuhashi",
        "actors": "Takuya Eguchi, Atsumi Tanezaki, Saori Hayami",
        "startDate": "10/02/2024",
        "duration": "111",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "NIGHT SWIM",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/02/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-14.jpg",
        "ageLimit": "T18",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Horror",
        "description": "Bơi Đêm dựa trên phim ngắn nổi tiếng năm 2014 của Bryce McGuire và Rod Blackhurst, kể về một người phụ nữ bơi trong hồ bơi vào ban đêm và bị thế lực ma quỷ tấn công.",
        "directors": "Bryce McGuire",
        "actors": "Wyatt Russell, Kerry Condon, Amelie Hoeferle",
        "startDate": "23/02/2024",
        "duration": "99",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "THE EXORCISTS",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/02/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-3.jpg",
        "ageLimit": "T18",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Horror",
        "description": "Để cứu gia đình mình, một người cha đã thuê 3 chuyên gia trừ tà để đánh bại con quỷ chiếm lấy con của ông.",
        "directors": "Jose Prendes",
        "actors": "Doug Bradley, Kayla Fields",
        "startDate": "23/02/2024",
        "duration": "84",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "DOG DAYS",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/02/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-8.jpg",
        "ageLimit": "K",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Comedy",
        "description": "Cuộc sống độc thân ưa ngăn nắp và ghét động vật của chủ nhà Min-sang bị đảo lộn khi nữ bác sĩ Jin-young tới thuê và mở phòng khám thú y, nhưng sau đó Min-sang phải học cách yêu chó để lấy lòng vị kiến trúc sư nổi tiếng Min-seo…",
        "directors": "Kim Deok-min",
        "actors": "Yoon Yuh-Jung, Kim Yun-Jin, Yu Hae-Jin",
        "startDate": "23/02/2024",
        "duration": "120",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "SILENT LOVE",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/03/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-4.jpg",
        "ageLimit": "T16",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Romance",
        "description": "Chỉ cần tình yêu. Trong thời đại phức tạp và lầy lội này, đây là câu chuyện tình buồn nhất mùa đông năm nay, nhẹ nhàng nâng niu một tình yêu trong sáng, trong sáng.",
        "directors": "Eiji Uchida",
        "actors": "Minami Hamabe, Arata Furuta",
        "startDate": "08/03/2024",
        "duration": "115",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "DUNE: PART II",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/02/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-2.jpg",
        "ageLimit": "T16",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Action",
        "description": "Một cậu bé trở thành Đấng cứu thế của những người du mục trên một hành tinh sa mạc có những con sâu khổng lồ bảo vệ một loại hàng hóa có tên là Spice. Anh ta sẽ trả cái giá nào để trở thành người cai trị mới của vũ trụ ?",
        "directors": "Denis Villeneuve",
        "actors": "Denis Villeneuve, Jon Spaihts, Timothée Chalamet",
        "startDate": "01/03/2024",
        "duration": "120",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "CITIZEN OF A KIND",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/02/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-13.jpg",
        "ageLimit": "C16",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Comedy",
        "description": "Sau khi cửa hàng giặt là của mình bị cháy, bà mẹ đơn thân Deok-hee nhận được cuộc gọi từ ngân hàng đề nghị cho vay trả trước hậu hĩnh nên cô nhận ngay. Nhưng ngay sau đó, cô phát hiện ra rằng mình đã trở thành nạn nhân của âm mưu lừa đảo bằng giọng nói.",
        "directors": "Young-ju Park",
        "actors": "Byeong-eun Park, Eun-jin Ahn",
        "startDate": "01/03/2024",
        "duration": "114",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "BAGHEAD",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/02/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-12.jpg",
        "ageLimit": "T18",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Horror",
        "description": "Một phụ nữ trẻ thừa kế một quán rượu xuống cấp và phát hiện ra bí mật đen tối bên trong tầng hầm của nó – Baghead – một sinh vật có thể thay đổi hình dạng cho phép bạn nói chuyện với những người thân yêu đã mất, nhưng cái giá phải trả rất đắt.",
        "directors": "Alberto Corredor",
        "actors": "Freya Allan, Jeremy Irvine",
        "startDate": "01/03/2024",
        "duration": "94",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "CELLPHONE",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/02/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-16.jpg",
        "ageLimit": "T16",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Horror",
        "description": "Wynne mắc chứng rối loạn căng thẳng sau cái chết của chồng sắp cưới bắt đầu nhìn thấy những hình ảnh đáng lo ngại trên điện thoại di động về tương lai của cô ấy. Nếu không phát hiện ra kịp thời, cô ấy sẽ chết.",
        "directors": "Luke Sommer",
        "actors": "Justin Malik Jackson, Whitney Rose Pynn",
        "startDate": "01/03/2024",
        "duration": "88",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    },
    {
        "movieName": "QUÝ CÔ THỪA KẾ 2",
        "image": "https://bhdstar.vn/wp-content/uploads/2024/03/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-1.jpg",
        "ageLimit": "T16",
        "language": "Phụ đề",
        "format": "2D",
        "cats": "Drama",
        "description": "Bộ phim kể về gia đình tưởng chừng như đầm ấm và hạnh phúc của Cao Minh, Hải Đường và con gái Kim. Tuy nhiên, mọi thứ ngày càng trở nên kì lạ khi Cao Minh càng lúc càng thô bạo và có xu hướng kiểm soát đầy độc hại lên cả vợ và con gái mình.",
        "directors": "Hoàng Duy",
        "actors": "Trang Nhung, Otis Nhật Trường, Huy Khánh, Lâm Vỹ Dạ",
        "startDate": "08/03/2024",
        "duration": "110",
        "endDate": "20/12/2024",
        "ticketOnSale": true
    }
]
